/* Generate rom_images.h from the binary ROM images. */

#include <errno.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define OUTPUT_PATH "kd11ea/roms/rom_images.h"
#define TEMP_PATH   "kd11ea/roms/rom_images.h.tmp"
#define MAX_ROM_SIZE 1024

typedef struct RomImage {
    const char *board;
    unsigned ref;
    size_t size;
    unsigned width;
    const char *symbol;
    const char *group;
} RomImage;

#define PRIMARY(ref) \
    { "M8266", ref, 512, 4, "m8266_e" #ref "_ucode_rom", "M8266 primary microcode, MPC09=0 bank" }
#define COMBO(board, ref, size, width) \
    { board, ref, size, width, "e" #ref "_rom", board " combinatorial ROMs" }
#define M8265_COMBO(ref, size, width) \
    { "M8265", ref, size, width, "m8265_e" #ref "_rom", "M8265 combinatorial ROMs" }

static const RomImage images[] = {
    PRIMARY(97), PRIMARY(98), PRIMARY(99), PRIMARY(100),
    PRIMARY(103), PRIMARY(104), PRIMARY(105), PRIMARY(106),
    PRIMARY(107), PRIMARY(108), PRIMARY(109), PRIMARY(110),

    COMBO("M8266", 29, 256, 4),  COMBO("M8266", 51, 32, 8),
    COMBO("M8266", 52, 1024, 4),
    COMBO("M8266", 53, 256, 4),  COMBO("M8266", 54, 256, 4),
    COMBO("M8266", 59, 256, 4),  COMBO("M8266", 60, 256, 4),
    COMBO("M8266", 61, 256, 4),  COMBO("M8266", 62, 256, 4),
    COMBO("M8266", 63, 256, 4),  COMBO("M8266", 68, 512, 4),
    COMBO("M8266", 69, 256, 4),  COMBO("M8266", 70, 512, 4),
    COMBO("M8266", 71, 256, 4),  COMBO("M8266", 74, 32, 8),
    COMBO("M8266", 80, 256, 4),  COMBO("M8266", 82, 32, 8),
    COMBO("M8266", 83, 32, 8),   COMBO("M8266", 87, 32, 8),
    COMBO("M8266", 102, 32, 8),

    M8265_COMBO(74, 256, 4), M8265_COMBO(75, 256, 4),
    M8265_COMBO(76, 256, 4), M8265_COMBO(77, 256, 4),
    M8265_COMBO(83, 256, 4), M8265_COMBO(86, 256, 4),
    COMBO("M8265", 107, 256, 4),
};

static int read_image(const RomImage *image, uint8_t data[MAX_ROM_SIZE]) {
    char path[128];
    FILE *file;
    size_t count;
    int extra;

    snprintf(path, sizeof(path), "kd11ea/roms/%s/E%u.bin",
             image->board, image->ref);
    file = fopen(path, "rb");
    if (!file) {
        fprintf(stderr, "%s: %s\n", path, strerror(errno));
        return 0;
    }

    count = fread(data, 1, image->size, file);
    extra = fgetc(file);
    if (ferror(file)) {
        fprintf(stderr, "%s: read error\n", path);
        fclose(file);
        return 0;
    }
    fclose(file);

    if (count != image->size || extra != EOF) {
        fprintf(stderr, "%s: expected %zu bytes, found %s%zu\n", path,
                image->size, extra == EOF ? "" : "more than ", count);
        return 0;
    }

    if (image->width == 4) {
        for (size_t i = 0; i < count; i++) {
            if (data[i] & 0xF0) {
                fprintf(stderr,
                        "%s: 4-bit ROM value 0x%02X at address 0x%zX\n",
                        path, data[i], i);
                return 0;
            }
        }
    }
    return 1;
}

static int emit_array(FILE *out, const RomImage *image,
                      const uint8_t data[MAX_ROM_SIZE]) {
    if (fprintf(out, "static const uint8_t %s[%zu] = {\n",
                image->symbol, image->size) < 0)
        return 0;

    for (size_t offset = 0; offset < image->size; offset += 16) {
        if (fputs("    ", out) == EOF)
            return 0;
        for (size_t i = offset; i < image->size && i < offset + 16; i++) {
            if (fprintf(out, "0x%02X,", data[i]) < 0)
                return 0;
            if (i + 1 < image->size && i + 1 < offset + 16 &&
                fputc(' ', out) == EOF)
                return 0;
        }
        if (fputc('\n', out) == EOF)
            return 0;
    }
    return fputs("};\n\n", out) != EOF;
}

int main(void) {
    uint8_t data[MAX_ROM_SIZE];
    const char *last_group = NULL;
    FILE *out = fopen(TEMP_PATH, "w");

    if (!out) {
        fprintf(stderr, "%s: %s\n", TEMP_PATH, strerror(errno));
        return EXIT_FAILURE;
    }

    fputs("/* Auto-generated by kd11ea/roms/gen_rom_header.c.  Do not edit. */\n"
          "#ifndef KD11EA_ROM_IMAGES_H\n"
          "#define KD11EA_ROM_IMAGES_H\n\n"
          "#include <stdint.h>\n\n", out);

    for (size_t i = 0; i < sizeof(images) / sizeof(images[0]); i++) {
        const RomImage *image = &images[i];
        if (!last_group || strcmp(last_group, image->group) != 0) {
            if (fprintf(out, "/* %s. */\n", image->group) < 0)
                goto write_error;
            last_group = image->group;
        }
        if (!read_image(image, data) || !emit_array(out, image, data))
            goto error;
    }

    if (fputs("#endif /* KD11EA_ROM_IMAGES_H */\n", out) == EOF)
        goto write_error;
    if (fclose(out) != 0) {
        out = NULL;
        goto write_error;
    }
    out = NULL;

    if (rename(TEMP_PATH, OUTPUT_PATH) != 0) {
        fprintf(stderr, "%s: %s\n", OUTPUT_PATH, strerror(errno));
        remove(TEMP_PATH);
        return EXIT_FAILURE;
    }
    printf("generated %s\n", OUTPUT_PATH);
    return EXIT_SUCCESS;

write_error:
    fprintf(stderr, "%s: write error\n", TEMP_PATH);
error:
    if (out)
        fclose(out);
    remove(TEMP_PATH);
    return EXIT_FAILURE;
}
